import { environment } from "../../../environments/environment";

const env = environment;
const urlBase = env.linkurl;

export const APP_IMAGES = {
    // logo
    logo: `${urlBase}public/images/logo.png`,
    logo2: `${urlBase}public/images/logo2.png`,
    logocolor: `${urlBase}public/images/logocolor.png`,
    logopet: `${urlBase}public/images/logo-pet.png`,
    // home
    home: `${urlBase}public/images/home.png`,
    hero1: `${urlBase}public/images/hero1.png`,
    hero2: `${urlBase}public/images/hero2.jpg`,
    identity: `${urlBase}public/images/indentity.png`,
    mission1: `${urlBase}public/images/mission1.png`,
    mission2: `${urlBase}public/images/mission2.png`,
    // durable
    durable: `${urlBase}public/images/durable/durable.png`,
    durableADN: `${urlBase}public/images/durable/ADN.png`,
    durablestrategie: `${urlBase}public/images/durable/strategie.png`,  
    // contact
    contactsupport: `${urlBase}public/images/contact/support.png`, 
    // events 
    eventAnnualMeeting: `${urlBase}public/images/events/AnnualMeeting.png`,
    eventBreadcrumb: `${urlBase}public/images/events/event-breadcrumb.png`,
    eventTalks: `${urlBase}public/images/events/top-management-talks.png`,
    // expertise
    expertiseGroupDiverse: `${urlBase}public/images/expertise/group-diverse-business-people.png`,
    expertiseConseil: `${urlBase}public/images/expertise/CONSEIL.svg`,
    expertiseComites: `${urlBase}public/images/expertise/Comités.svg`,
    expertiseOrganes: `${urlBase}public/images/expertise/Organes-fonctionnels.svg`,
    expertiseexpclinet: `${urlBase}public/images/expertise/expclinet.png`,
    expertiseexpemploye: `${urlBase}public/images/expertise/expemploye.png`,
    expertisecompetence: `${urlBase}public/images/expertise/competence.png`,
    expertisediversite: `${urlBase}public/images/expertise/diversité.png`,
    expertisedigitaltech: `${urlBase}public/images/expertise/digitaltech.png`,
    expertiseconduitetransofrmat: `${urlBase}public/images/expertise/conduitetransofrmat.svg`,
    // profils
    profilszaid: `${urlBase}public/images/profils/zaid.png`,
    profilsdupont: `${urlBase}public/images/profils/dupont.png`,
    profilsdubois: `${urlBase}public/images/profils/dubois.png`,
    profillouise: `${urlBase}public/images/profils/louise.png`,
    profillouise1: `${urlBase}public/images/profils/louise1.png`,
    profilsmith: `${urlBase}public/images/profils/smith.png`,
    profilbenkirane: `${urlBase}public/images/profils/benkirane.png`,
    profilwilliams: `${urlBase}public/images/profils/williams.png`,
    // Leader
    leader1: `${urlBase}public/images/expertise/leader1.svg`,
    leader2: `${urlBase}public/images/expertise/leader2.svg`,
    leader3: `${urlBase}public/images/expertise/leader3.svg`,
    leader4: `${urlBase}public/images/expertise/leader4.svg`,
    // partners
    partnerToyota: `${urlBase}public/images/partners/toyota.png`,
    partenerInicambridge: `${urlBase}public/images/partners/unicambridge.png`,
    partnerSpotify: `${urlBase}public/images/partners/spotify.png`,
    partnerQatar: `${urlBase}public/images/partners/qatarairways.png`,
    partnerBooking: `${urlBase}public/images/partners/booking.png`,
    partnerMicrosoft: `${urlBase}public/images/partners/microsoft.png`,
    partnerHespress: `${urlBase}public/images/partners/hespress.png`,
    // politique
    politiqueleader: `${urlBase}public/images/politique/leader.png`,
    politiquebronze: `${urlBase}public/images/politique/bronze.svg`,
    politiqueannoncespons: `${urlBase}public/images/politique/annoncespons.svg`,
    politiquecfmiMaroc: `${urlBase}public/images/politique/cfmi-maroc.svg`,
    politiqueBronze: `${urlBase}public/images/politique/bronze.svg`,
    politiqueAnnonceSpons: `${urlBase}public/images/politique/annoncespons.svg`,
    politiqueCfmiMaroc: `${urlBase}public/images/politique/cfmi-maroc.svg`,
    politiqueGold: `${urlBase}public/images/politique/gold.svg`,
    // searchLab
    searchlab: `${urlBase}public/images/searchLab/researchLab.png`,
    searchlabmissionDuLabo: `${urlBase}public/images/searchLab/missionDuLabo.png`,
    searchlaborientationRapport: `${urlBase}public/images/searchLab/orientationRapport.png`,
    searchlabprogramme: `${urlBase}public/images/searchLab/searchProg.png`,
    // Others
    worldMap: `${urlBase}public/images/world-map.png`,
    subscribeNewsletter: `${urlBase}public/images/subscribeNewsletter.png`, 
    // Offres
    offresTransformation: `${urlBase}public/images/offres/TRANSFORMATION.svg`, 
    offresBread: `${urlBase}public/images/offres/breadoffre.png`,
    offresGouvernance: `${urlBase}public/images/offres/gouvernance-partner.svg`,
    offresStrategy: `${urlBase}public/images/offres/strategy.svg`,
    offresCapitalHumain: `${urlBase}public/images/offres/capitalhumain.svg`,
    offresCrown: `${urlBase}public/images/offres/crown.svg`,
    offresReferralAlt: `${urlBase}public/images/offres/referral-alt.svg`,
    offresHeadset: `${urlBase}public/images/offres/headset.svg`,
    offresRessources: `${urlBase}public/images/offres/ressources.svg`,
    offresTypemaster: `${urlBase}public/images/offres/typmaster.png`,
};
